### ISSUE TITLE
Saving a wp.plot rather than opening in browser

### ISSUE THREAD

**Issue by ilv18** [dylanwal/well_plate#1]
Hi, how can we save the wp.plot rather than it opening in the browser? 

fig = wp.plot(auto_open=False)
fig.savefig(todayDate + "_wellplate.png")

^^ I tried this code but it doesn't work, and have also tried the fig.write_image suggested method. Any help would be amazing!

**Comment by dylanwal** [comment]
Do you get an error with `fig.write_image()`? If so, could you copy and paste it here?

**Comment by dylanwal** [comment]
Closing the issue due to inactivity. Re-open if you have error message.
